interface management 
  ip address dhcp 
!
interface ethernet 1 
!
interface ethernet 2 
!
interface ethernet 3 
!
interface ethernet 4 
!
interface ethernet 5 
!
interface ethernet 6 
!
interface ethernet 7 
!
interface ethernet 8 
!
interface ethernet 9 
!
interface ethernet 10 
!
interface ethernet 11 
!
interface ethernet 12 
!
interface ethernet 13 
!
interface ethernet 14 
!
interface ethernet {INSIDE_PORT} 
  enable 
  ip address 10.255.0.1 255.255.255.252 
  ip nat inside 
! 
interface ethernet {OUTSIDE_PORT} 
  enable 
  ip address 10.255.0.5 255.255.255.252 
  ip nat outside 
! 
!
ip route 100.64.0.0 /10 10.255.0.2 
!
ip route 100.64.1.0 /24 10.255.0.2 
!
ip route 198.18.0.0 /24 10.255.0.6 
!
ip route 198.18.1.0 /24 10.255.0.6 
!
class-list CGN 
  100.64.0.0/10 lsn-lid 1 
!
cgnv6 template pcp PCP 
  allow-third-party-from-lan 
  allow-third-party-from-wan 
!
cgnv6 template http-alg HTTP_ALG 
!
cgnv6 lsn alg esp enable 
!
cgnv6 lsn alg pptp enable 
!
cgnv6 lsn alg rtsp enable 
!
cgnv6 lsn alg sip enable 
!
cgnv6 lsn alg mgcp enable 
!
cgnv6 lsn alg h323 enable 
!
cgnv6 lsn alg tftp enable 
!
cgnv6 lsn endpoint-independent-mapping tcp 
  port 1 to 65535 
!
cgnv6 lsn endpoint-independent-mapping udp 
  port 1 to 65535 
!
cgnv6 lsn endpoint-independent-filtering tcp 
  port 1 to 65535 
!
cgnv6 lsn endpoint-independent-filtering udp 
  port 1 to 65535 
!
cgnv6 lsn inside source class-list CGN 
!
cgnv6 nat pool lsn 203.0.113.1 203.0.113.254 netmask /24 max-users-per-ip 128 port-batch-v2-size 512 simultaneous-batch-allocation 
!
cgnv6 lsn-lid 1 
  respond-to-user-mac 
  source-nat-pool lsn 
!
sflow setting local-collection 
!
sflow collector ip 127.0.0.1 6343 
!
!
end
!